name: Generate PyPI Index
on:
  push:
    branches:
      - main

jobs:
  build_grpcio:
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - name: Checkout GitHub Repo
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Build wheels
        run: bash pypi/projects/grpcio/build-macos.sh
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Build grpcio wheels
          file_pattern: pypi/projects/grpcio/*.whl pypi/projects/grpcio-tools/*.whl
  generate_index:
    needs: [build_grpcio]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repo (+ download lfs dependencies)
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Checkout repository with gh-pages branch
        uses: actions/checkout@v3
        with:
          lfs: true
          path: pages-output
          ref: gh-pages
      - name: Generate Index
        run: python scripts/generate_pypi.py
        env:
          REPOSITORY: lablup/backend.ai-oven
          BRANCH: main
          OUTPUT_DIRECTORY: pages-output/pypi
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: pages-output
          commit_message: Generate PyPI index.html
          file_pattern: pypi/hash-lock.json pypi/index.html pypi/package/*.html pypi/simple/*.html pypi/simple/**/*.html
